version: "3.8"
services:
  dynamo:
    container_name: local-dynamodb
    image: amazon/dynamodb-local
    networks:
      - local-dynamodb
    ports:
      - "8002:8002"
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -port 8002 -dbPath ."
networks:
  local-dynamodb:
    name: local-dynamodb

volumes:
  dynamodata: {}
